### ISSUE TITLE
Tasksheet 2

### ISSUE THREAD

**Issue by jotoho** [jotoho/cpp2-praktikum#4]
This week's task revolves around taking the previous work under `/1/` and expanding on it with more features.

### Tasks

The following things are required of us:

 * [x] Copy contents of `1/` into folder `2/` (Done. See c33d225654a6051e4798b4cab944fac02c6a68f3)
 * [x] Rework the `Stack` class to use dynamically allocated memory, instead of a statically sized array on the stack.
 * [x] Implement the following prototypes as methods of the class:
   * [x] `Stack();`
   * [x] `Stack(const Stack&);`
   * [x] `~Stack();`
   * [x] `const Stack& operator=(const Stack&);`
 * [x] Modify the `Stack::push(int)` method such that pushes to a full Stack allocates a larger block of memory, copies over the existing contents, frees the old block and adds the parameter to the new block of memory.
 
### Open questions

 * [x] The tasks explicitly mention that the type of the storage block should be changed from `int[]` to `int*`. Should we take this to mean, that we cannot use a reliable storage structure, like a `std::vector` internally and avoid all memory management headaches?
 **Yes, the type needs to be int***
 * [x] The description of changes required to `Stack::push(int)` explicitly mentions copying the memory over. Does this mean we need to do so manually ourselves or can we use C stdlib functionality like `realloc()`?
 **We can use realloc**

**Comment by jotoho** [comment]
It seems there should be a private static setting determining the amount of space made for new elements every time the capacity needs to be increased.

**Comment by TimBeckmann** [comment]
We also needed to change `Stack::pop()` and `Stack::peek()`.
